.TH GunRC 1 "20.06.14"
.SH NAME
GunRC \- GTK Universal Network Remote Control
.SH SYNOPSIS
.B gunrc
[\fIOPTION\fR]
.SH DESCRIPTION
GunRC is a GTK+ based remote control for network devices.
.SH OPTIONS
.TP
.B \-h\fR, \fB\-\-help
Show this help and exit
.TP
.B \-p\fR, \fB\-\-popup
Popup song notification (requires D\-Bus)
.TP
.B \-t\fR, \fB\-\-toggle
Toggles whether the app is minimized to tray or visible (requires D\-Bus)
.PP
This manual page is currently maintained by Jonas Enge
<jonas.enge@gmail.com>.
